apiVersion: v1
kind: Secret
metadata:
  name: kube-database-api
type: Opaque
data:
  connectionString: RGF0YSBTb3VyY2U9aG9zdC5kb2NrZXIuaW50ZXJuYWw7SW5pdGlhbCBDYXRhbG9nPXRvZG9fZGI7VXNlciBJZD1zYTtQYXNzd29yZD1ZT1VSX1BBU1NXT1JEX0hFUkU7RW5saXN0PWZhbHNlO1RydXN0U2VydmVyQ2VydGlmaWNhdGU9dHJ1ZQ==
