apiVersion: v1
kind: Service
metadata:
  name: kube-database-api
spec:
  selector:
    app: kube-database-api # matches the pod label
  type: ClusterIP # NodePort, ExternalName, LoadBalancer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
