apiVersion: v1
kind: Service
metadata:
  name: kube-webapp
spec:
  selector:
    app: kube-webapp
  type: ClusterIP # NodePort, ExternalName, LoadBalancer
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 80
